// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

#pragma warning disable ASPIREDOCKERFILEBUILDER001

using Aspire.Hosting.ApplicationModel;
using Aspire.Hosting.ApplicationModel.Docker;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace Aspire.Hosting.Rust;

/// <summary>
/// Generates the multi-stage Dockerfile that publishes a <see cref="RustAppResource"/>.
/// </summary>
/// <remarks>
/// The container build is the only build: nothing here compiles the crate on the host. The single piece of
/// host-side information the Dockerfile needs is the name of the binary cargo will produce, which comes from
/// <c>cargo metadata</c> — a manifest query that neither compiles nor downloads dependencies.
/// </remarks>
internal static class RustDockerfileGenerator
{
    // Cargo's output directory inside the build stage. The build context is copied wholesale, so a crate's
    // .cargo/config.toml comes with it and its build.target-dir would otherwise move the binary somewhere the
    // COPY --from below does not look. Pinning it to a path outside /app also keeps build output away from the
    // copied sources.
    private const string ContainerTargetDirectory = "/build/target";

    // Default .dockerignore emitted next to the generated Dockerfile using BuildKit's per-Dockerfile ignore
    // convention. The build stage does `COPY . .`, so without this a local `target/` directory is uploaded to
    // the daemon as build context and copied into the build stage: it is routinely several gigabytes after a
    // debug run, and none of it is usable because the container rebuilds from source anyway. Cargo places a
    // target directory next to every manifest it is invoked against, hence the recursive pattern as well.
    // A .dockerignore authored at the context root takes precedence over this file, so a crate that needs
    // something listed here (a build script reading .git, for example) can opt out.
    // See https://docs.docker.com/build/concepts/context/#filename-and-location.
    private const string DefaultRustBuildContextIgnoreContent = """
        # Generated by Aspire. Author <contextRoot>/.dockerignore to override.
        target
        **/target
        .git
        .gitignore
        .DS_Store
        .env
        .env.*
        .aspire
        aspire-output
        Dockerfile
        Dockerfile.*
        *.Dockerfile
        *.Dockerfile.dockerignore
        .dockerignore

        """;

    public static async Task WriteAsync(RustAppResource resource, string appDirectory, DockerfileBuilderCallbackContext context)
    {
        var logger = context.Services.GetService<ILogger<RustAppResource>>();

        // Guarded because WithDockerfileBuilder always adds the annotation, but this stays robust if that
        // changes. Only set when nothing else has, so an explicit choice by the user or a future caller wins.
        if (context.Resource.TryGetLastAnnotation<DockerfileBuildAnnotation>(out var dockerfileBuildAnnotation))
        {
            dockerfileBuildAnnotation.BuildContextIgnoreContent ??= DefaultRustBuildContextIgnoreContent;
        }

        // Target selection comes from the options annotation rather than from the argument list: those are
        // the values that decide which file ends up under target/, and reading them here keeps publish in
        // step with whatever the WithCargo* methods emitted into the argument list.
        var options = resource.TryGetLastAnnotation<RustCargoOptionsAnnotation>(out var cargoOptions)
            ? cargoOptions
            : new RustCargoOptionsAnnotation();

        var metadata = await context.Services.GetRequiredService<ICargoMetadataReader>()
            .ReadAsync(appDirectory, options.ManifestPath, resource.Name, context.CancellationToken)
            .ConfigureAwait(false);
        var target = RustCargoTargetResolver.Resolve(
            metadata,
            options,
            context.Services.GetRequiredService<DistributedApplicationExecutionContext>(),
            resource.Name);

        // Cargo args must come from the same annotation pipeline that run mode uses, otherwise
        // WithCargoArgs/WithCargoFeatures configuration silently changes meaning at publish time. They are
        // read from `resource` rather than context.Resource because the latter is the ContainerResource that
        // PublishAsDockerFile substitutes in, which does not carry the Rust annotations.
        var cargoArgs = await ResolvePublishCargoArgsAsync(resource, options, metadata, context.CancellationToken).ConfigureAwait(false);

        // A manifest path configured for the host points somewhere that does not exist in the container, so
        // the copy of it that reaches `cargo build` has to be rewritten to sit under /app.
        if (options.ManifestPath is { } manifestPath)
        {
            RewriteManifestPath(cargoArgs, manifestPath, ToContainerPath(manifestPath, appDirectory, resource.Name));
        }

        var baseImageAnnotation = ResolveBaseImageAnnotation(resource, context);
        var images = RustPublishImageResolver.Resolve(
            baseImageAnnotation?.BuildImage,
            baseImageAnnotation?.RuntimeImage,
            appDirectory,
            metadata.MinimumRustVersion,
            resource.Name);

        var buildStage = context.Builder
            .From(images.BuildImage, "build")
            .WorkDir("/app");

        if (images.BuildImageIsAlpine)
        {
            // The rust:*-alpine images ship the Rust toolchain but no C toolchain. Any crate with native
            // dependencies (ring and aws-lc-sys via rustls, openssl-sys, and anything using the cc crate)
            // fails to link without these. Installing them unconditionally keeps the common TLS/OTLP
            // configuration working out of the box.
            // See https://github.com/rust-lang/docker-rust/issues/85
            buildStage.Run("apk add --no-cache musl-dev gcc");
        }

        if (target.Target is { } triple)
        {
            // A cross target's standard library is not present in the base image, so it has to be installed
            // before cargo can build for it.
            buildStage.Run($"rustup target add {ShellQuote(triple)}");
        }

        buildStage
            .Copy(".", ".")
            // Cache the downloaded crate registry across builds. The target directory is deliberately NOT a
            // cache mount: cache mounts are not part of the resulting layer, so the COPY --from below would
            // not be able to see the binary.
            // CARGO_HOME is /usr/local/cargo in the official rust images; a cache mount on a path a custom
            // build image does not use is harmless.
            .RunWithMounts(
                BuildCargoCommand(cargoArgs),
                "type=cache,target=/usr/local/cargo/registry");

        // Add intermediate FROM stages for any container files sources (e.g. FROM frontend AS frontend_stage).
        context.Builder.AddContainerFilesStages(context.Resource, logger);

        var runtimeStage = context.Builder.From(images.RuntimeImage);

        // The default runtime image is Alpine, so the hardening steps below use apk and BusyBox
        // adduser/addgroup flags. A caller-supplied runtime image can be any distro (for example
        // debian:bookworm-slim when pairing with a glibc build image), where `apk` does not exist and
        // `adduser -S` is not valid syntax.
        if (images.RuntimeImageIsAlpine)
        {
            runtimeStage
                .Run("apk --no-cache add ca-certificates tzdata")
                .Run("addgroup -S app && adduser -S -G app app");
        }
        else
        {
            // The image name is only a hint — a private image can be built on Alpine and named anything — so
            // try the BusyBox commands first and fall back to shadow-utils rather than assuming the glibc
            // tooling. The ids are pinned so a mounted volume sees the same owner either way.
            runtimeStage.Run(
                "(addgroup -g 999 -S app || groupadd --system --gid 999 app) && " +
                "(adduser -u 999 -S -G app app || useradd --system --uid 999 --gid 999 --no-create-home app)");
        }

        runtimeStage
            .WorkDir("/app")
            // Add COPY --from=<source> instructions for each container files source.
            .AddContainerFiles(context.Resource, "/app", logger)
            // RelativePath is relative to cargo's target directory, which the build stage pins to a fixed
            // location so the crate's own configuration cannot move it.
            .CopyFrom("build", $"{ContainerTargetDirectory}/{target.RelativePath}", $"/app/{target.Name}")
            .User("app")
            .Entrypoint([$"/app/{target.Name}"]);
    }

    // Evaluates every cargo args callback exactly as run mode does, then applies the defaults that only
    // publishing opts into. Both are appended only when the resource expressed no preference: an explicit
    // WithCargoReleaseBuild/WithCargoLocked has already put its flag in the list, and an explicit `false`
    // means the published image deliberately does without.
    private static async Task<List<string>> ResolvePublishCargoArgsAsync(
        RustAppResource resource,
        RustCargoOptionsAnnotation options,
        CargoMetadata metadata,
        CancellationToken cancellationToken)
    {
        var args = new List<string>();

        foreach (var annotation in resource.Annotations.OfType<RustCargoArgsCallbackAnnotation>())
        {
            await annotation.Callback(new RustCargoArgsCallbackContext(args, cancellationToken)).ConfigureAwait(false);
        }

        var cargoArgs = args.Where(static arg => arg.Length > 0).ToList();

        // --locked fails the build rather than writing a lock file, so a published image can only build the
        // dependency versions that were committed. It is only safe to add when a lock file actually exists;
        // cargo errors out with "the lock file needs to be updated but --locked was passed" otherwise, which
        // would break publishing for crates that deliberately do not commit one (libraries, mostly).
        if (options.Locked is null && HasLockFile(metadata))
        {
            cargoArgs.Add("--locked");
        }

        // Cargo rejects --release alongside --profile, so a resource that named a profile is already optimized
        // as it asked to be.
        if (options.Profile is null && options.ReleaseBuild is null)
        {
            cargoArgs.Add("--release");
        }

        // Appended last because cargo takes the last occurrence of a flag, so this overrides a --target-dir
        // that reached the list some other way as well as the crate's own configuration.
        cargoArgs.Add("--target-dir");
        cargoArgs.Add(ContainerTargetDirectory);

        return cargoArgs;
    }

    // Cargo keeps a single lock file for the whole workspace, next to the root manifest.
    // See https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html
    private static bool HasLockFile(CargoMetadata metadata)
        => metadata.WorkspaceRoot is { Length: > 0 } workspaceRoot
            && File.Exists(Path.Combine(workspaceRoot, "Cargo.lock"));

    // The two-token form is what WithCargoManifestPath emits, so match on the pair rather than reformatting
    // the argument list. A --manifest-path passed as a raw string through WithCargoArgs is left alone, in
    // keeping with raw arguments being forwarded verbatim everywhere else.
    private static void RewriteManifestPath(List<string> cargoArgs, string hostPath, string containerPath)
    {
        for (var i = 0; i < cargoArgs.Count - 1; i++)
        {
            if (cargoArgs[i] == "--manifest-path" && cargoArgs[i + 1] == hostPath)
            {
                cargoArgs[i + 1] = containerPath;
            }
        }
    }

    // The app directory is the docker build context and is copied to /app, so a host path only has a
    // container equivalent when it sits inside that directory. A path outside it is not part of the build
    // context at all, so there is nothing to rewrite it to and no Dockerfile that could build the crate.
    private static string ToContainerPath(string hostPath, string appDirectory, string resourceName)
    {
        var relative = Path.GetRelativePath(appDirectory, Path.GetFullPath(hostPath, appDirectory));

        // GetRelativePath returns a rooted path when the two share no common root (different drives on
        // Windows), and a ..-prefixed path when the target is above the app directory.
        var escapesContext = Path.IsPathRooted(relative)
            || relative == ".."
            || relative.StartsWith("../", StringComparison.Ordinal)
            || relative.StartsWith(@"..\", StringComparison.Ordinal);

        if (escapesContext)
        {
            throw new DistributedApplicationException(
                $"The Rust app '{resourceName}' builds from '{hostPath}', which is outside its app directory '{appDirectory}'. " +
                $"Publishing copies only the app directory into the container image, so point the app directory at a location that " +
                $"contains the whole crate, or add a Dockerfile next to Cargo.toml to take over the container build.");
        }

        return relative is "." ? "/app" : $"/app/{relative.Replace('\\', '/')}";
    }

    private static string BuildCargoCommand(List<string> cargoArgs)
        => string.Join(" ", new[] { "cargo", "build" }.Concat(cargoArgs.Select(ShellQuote)));

    // Dockerfile RUN uses the shell form (/bin/sh -c), so user-supplied values such as bin target and feature
    // names must be quoted to avoid changing the command's meaning. Already-safe tokens (notably cargo's own
    // flags) are left bare so the generated Dockerfile stays readable.
    private static string ShellQuote(string value)
    {
        if (value.Length > 0 && value.All(static c => char.IsAsciiLetterOrDigit(c) || c is '-' or '_' or '.' or '/' or '=' or ',' or '+' or ':'))
        {
            return value;
        }

        // Single quotes suppress all shell expansion. An embedded single quote is emitted by closing the
        // quoted run, escaping the quote, then reopening: don't => 'don'\''t'.
        return $"'{value.Replace("'", "'\\''")}'";
    }

    // WithDockerfileBaseImage may be applied either to the Rust resource builder or, inside the
    // PublishAsDockerFile callback, to the substituted container resource. Check both so the override works
    // wherever the user attaches it.
    private static DockerfileBaseImageAnnotation? ResolveBaseImageAnnotation(RustAppResource resource, DockerfileBuilderCallbackContext context)
        => context.Resource.Annotations.OfType<DockerfileBaseImageAnnotation>().LastOrDefault()
            ?? resource.Annotations.OfType<DockerfileBaseImageAnnotation>().LastOrDefault();
}

#pragma warning restore ASPIREDOCKERFILEBUILDER001
