// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

#pragma warning disable ASPIREDOCKERFILEBUILDER001

using System.Collections.ObjectModel;
using Aspire.Hosting.ApplicationModel;
using Aspire.Hosting.ApplicationModel.Docker;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace Aspire.Hosting.Rust;

/// <summary>
/// Generates the multi-stage Dockerfile that publishes a <see cref="RustAppResource"/>.
/// </summary>
/// <remarks>
/// The container build is the only build: nothing here compiles the crate on the host. The single piece of
/// host-side information the Dockerfile needs is the name of the binary cargo will produce, which comes from
/// <c>cargo metadata</c> — a manifest query that neither compiles nor downloads dependencies.
/// </remarks>
internal static class RustDockerfileGenerator
{
    // The unversioned tag tracks current stable, but is only a starting point: rustup is present in the
    // official image and installs whatever a rust-toolchain.toml pins, including nightly and beta.
    private const string DefaultBuildImage = "rust:alpine";

    // Paired with the musl build image above so the binary and the image it runs in share a libc by
    // construction. Pinned to a release so a generated Dockerfile does not silently cross a major version.
    private const string DefaultRuntimeImage = "alpine:3.24";

    // Outside /app so build output stays clear of the copied sources, and pinned so that a .cargo/config.toml
    // arriving with the build context cannot move the binary somewhere COPY --from does not look.
    private const string ContainerTargetDirectory = "/build/target";

    // Where the build stage leaves the binary at a path the runtime stage can predict.
    private const string ContainerArtifactDirectory = "/build/bin";

    // Emitted next to the generated Dockerfile using BuildKit's per-Dockerfile ignore convention. The build
    // stage does `COPY . .`, so without this the local target/ directory is uploaded to the daemon and copied
    // into the image: routinely several gigabytes, and useless because the container rebuilds from source.
    // Cargo places a target directory next to every manifest, hence the recursive pattern too.
    // See https://docs.docker.com/build/concepts/context/#filename-and-location.
    private const string DefaultRustBuildContextIgnoreContent = """
        # Generated by Aspire. Author <contextRoot>/.dockerignore to take over these rules.
        target
        **/target
        .git
        .gitignore
        .DS_Store
        .env
        .env.*
        .aspire
        aspire-output
        Dockerfile
        Dockerfile.*
        *.Dockerfile
        *.Dockerfile.dockerignore
        .dockerignore

        """;

    public static async Task WriteAsync(RustAppResource resource, string appDirectory, DockerfileBuilderCallbackContext context)
    {
        var logger = context.Services.GetService<ILogger<RustAppResource>>();

        // A <dockerfile>.dockerignore takes precedence over the context root's .dockerignore rather than
        // merging with it, so an authored one wins outright rather than being silently discarded.
        if (context.Resource.TryGetLastAnnotation<DockerfileBuildAnnotation>(out var dockerfileBuildAnnotation)
            && !File.Exists(Path.Combine(appDirectory, ".dockerignore")))
        {
            dockerfileBuildAnnotation.BuildContextIgnoreContent ??= DefaultRustBuildContextIgnoreContent;
        }

        // Target selection reads the options annotation rather than the argument list, because those are the
        // values that decide which file ends up under target/.
        var options = resource.TryGetLastAnnotation<RustCargoOptionsAnnotation>(out var cargoOptions)
            ? cargoOptions
            : new RustCargoOptionsAnnotation();

        var metadata = await context.Services.GetRequiredService<ICargoMetadataReader>()
            // Queried with an empty environment: the resource's environment applies to the process the
            // container runs, not to this host-side manifest query.
            .ReadAsync(appDirectory, options.ManifestPath, resource.Name, ReadOnlyDictionary<string, string>.Empty, context.CancellationToken)
            .ConfigureAwait(false);

        // Cargo cannot build a workspace member without the root manifest, and only the app directory is
        // copied into the image.
        if (metadata.WorkspaceRoot is { Length: > 0 } workspaceRoot && !IsInsideAppDirectory(workspaceRoot, appDirectory))
        {
            throw new DistributedApplicationException(
                $"The Rust app '{resource.Name}' is a member of the cargo workspace rooted at '{workspaceRoot}', which is outside its " +
                $"app directory '{appDirectory}'. Publishing copies only the app directory into the container image, so point the app " +
                $"directory at the workspace root and select the member with WithCargoPackage(\"<name>\"), or add a Dockerfile next to " +
                $"Cargo.toml to take over the container build.");
        }

        var target = RustCargoTargetResolver.Resolve(
            metadata,
            options,
            context.Services.GetRequiredService<DistributedApplicationExecutionContext>(),
            resource.Name);

        // Read from `resource` rather than context.Resource because the latter is the ContainerResource that
        // PublishAsDockerFile substitutes in, which does not carry the Rust annotations.
        var cargoArgs = await ResolvePublishCargoArgsAsync(resource, context.CancellationToken).ConfigureAwait(false);

        if (options.ManifestPath is { } manifestPath)
        {
            RewriteManifestPath(cargoArgs, manifestPath, ToContainerPath(manifestPath, appDirectory, resource.Name));
        }

        // Base images are used exactly as given, and nothing is installed into either: a name is free-form,
        // so a musl-based image can be called anything and an image whose name says otherwise can be
        // glibc-based underneath. Pairing images that can run what they build, including against any
        // --target, belongs to whoever overrides them.
        var baseImageAnnotation = ResolveBaseImageAnnotation(resource, context);

        var buildStage = context.Builder
            .From(baseImageAnnotation?.BuildImage ?? DefaultBuildImage, "build")
            .WorkDir("/app");

        if (target.Target is { } triple)
        {
            // A cross target's standard library is not present in the base image.
            buildStage.Run($"rustup target add {ShellQuote(triple)}");
        }

        buildStage
            .Copy(".", ".")
            // The target directory is deliberately NOT cache mounted: cache mounts are not part of the
            // resulting layer, so the COPY --from below would not see the binary. Neither is RUSTUP_HOME
            // (/usr/local/rustup), because a cache mount starts empty and shadows what it covers, hiding the
            // toolchains the image ships until rustup fails with no default toolchain configured.
            .RunWithMounts(
                $"{BuildCargoCommand(cargoArgs)}{CommandContinuation}{BuildCollectArtifactCommand(target)}",
                "type=cache,target=/usr/local/cargo/registry");

        // Add intermediate FROM stages for any container files sources (e.g. FROM frontend AS frontend_stage).
        context.Builder.AddContainerFilesStages(context.Resource, logger);

        var runtimeStage = context.Builder.From(baseImageAnnotation?.RuntimeImage ?? DefaultRuntimeImage);

        // BusyBox and shadow-utils disagree on both the command names and their flags, and the runtime image
        // may ship either, so try one and fall back to the other rather than guessing from the image name.
        //
        // The ids are left to the tool to allocate because no id is free on every image: alpine already uses
        // gid 999 for `ping`, and asking for a taken id fails outright rather than falling through to the
        // next command. An image needing a particular id can create the user itself in its own Dockerfile.
        runtimeStage.Run(
            "(addgroup -S app || groupadd --system app) && " +
            "(adduser -S -G app app || useradd --system --gid app --no-create-home app)");

        runtimeStage
            .WorkDir("/app")
            // Add COPY --from=<source> instructions for each container files source.
            .AddContainerFiles(context.Resource, "/app", logger)
            .CopyFrom("build", $"{ContainerArtifactDirectory}/{target.Name}", $"/app/{target.Name}")
            .User("app")
            .Entrypoint([$"/app/{target.Name}"]);
    }

    // Evaluates every cargo args callback exactly as run mode does — the publish-only defaults are added by
    // AddInitialCargoArgs, which sees the same execution context — then applies the container-only arguments.
    private static async Task<List<string>> ResolvePublishCargoArgsAsync(
        RustAppResource resource,
        CancellationToken cancellationToken)
    {
        var args = new List<string>();

        foreach (var annotation in resource.Annotations.OfType<RustCargoArgsCallbackAnnotation>())
        {
            await annotation.Callback(new RustCargoArgsCallbackContext(args, cancellationToken)).ConfigureAwait(false);
        }

        var cargoArgs = args.Where(static arg => arg.Length > 0).ToList();

        // Appended last because cargo takes the last occurrence of a flag, so this also overrides a
        // --target-dir that reached the list some other way.
        cargoArgs.Add("--target-dir");
        cargoArgs.Add(ContainerTargetDirectory);

        return cargoArgs;
    }

    // The two-token form is what WithCargoManifestPath emits. A --manifest-path passed as a raw string
    // through WithCargoArgs is left alone, in keeping with raw arguments being forwarded verbatim.
    private static void RewriteManifestPath(List<string> cargoArgs, string hostPath, string containerPath)
    {
        for (var i = 0; i < cargoArgs.Count - 1; i++)
        {
            if (cargoArgs[i] == "--manifest-path" && cargoArgs[i + 1] == hostPath)
            {
                cargoArgs[i + 1] = containerPath;
            }
        }
    }

    // The app directory is the docker build context and is copied to /app, so a host path only has a
    // container equivalent when it sits inside that directory.
    private static string ToContainerPath(string hostPath, string appDirectory, string resourceName)
    {
        if (!IsInsideAppDirectory(hostPath, appDirectory))
        {
            throw new DistributedApplicationException(
                $"The Rust app '{resourceName}' builds from '{hostPath}', which is outside its app directory '{appDirectory}'. " +
                $"Publishing copies only the app directory into the container image, so point the app directory at a location that " +
                $"contains the whole crate, or add a Dockerfile next to Cargo.toml to take over the container build.");
        }

        var relative = Path.GetRelativePath(appDirectory, Path.GetFullPath(hostPath, appDirectory));

        return relative is "." ? "/app" : $"/app/{relative.Replace('\\', '/')}";
    }

    private static bool IsInsideAppDirectory(string hostPath, string appDirectory)
    {
        var relative = Path.GetRelativePath(appDirectory, Path.GetFullPath(hostPath, appDirectory));

        // GetRelativePath returns a rooted path when the two share no common root (different drives on
        // Windows), and a ..-prefixed path when the target is above the app directory.
        return !Path.IsPathRooted(relative)
            && relative != ".."
            && !relative.StartsWith("../", StringComparison.Ordinal)
            && !relative.StartsWith(@"..\", StringComparison.Ordinal);
    }

    private static string BuildCargoCommand(List<string> cargoArgs)
        => string.Join(" ", new[] { "cargo", "build" }.Concat(cargoArgs.Select(ShellQuote)));

    // Moves the freshly built binary to a fixed path so the runtime stage's COPY --from does not have to know
    // whether cargo inserted a target-triple directory. `--target` is only one of the ways a triple is
    // selected — `[build] target` in a .cargo/config.toml arrives with the build context, and
    // CARGO_BUILD_TARGET can come from the resource environment — so both layouts are searched:
    //   /build/target/release/api            (no target selected)
    //   /build/target/x86_64-.../release/api (some target selected, by whatever means)
    // The emptiness test reports the miss directly; without it the failure is a bare `cp: cannot stat ''`.
    private static string BuildCollectArtifactCommand(RustCargoTarget target)
    {
        // Quoting only the suffix keeps the wildcard live: `/build/target/*/'my bin'` still globs, whereas
        // quoting the whole path would make the `*` literal.
        var suffix = ShellQuote(target.RelativePathWithoutTarget);
        var candidates = $"{ContainerTargetDirectory}/{suffix} {ContainerTargetDirectory}/*/{suffix}";
        var destination = $"{ContainerArtifactDirectory}/{ShellQuote(target.Name)}";

        return string.Join(
            CommandContinuation,
            [
                $"bin=\"$(ls -1d {candidates} 2>/dev/null | head -n1)\"",
                $"[ -n \"$bin\" ] || {{ echo \"cargo build produced no binary under {ContainerTargetDirectory}\" >&2; exit 1; }}",
                $"mkdir -p {ContainerArtifactDirectory}",
                $"cp \"$bin\" {destination}"
            ]);
    }

    // An explicit LF is used rather than Environment.NewLine or a raw string literal because a CR after the
    // backslash stops the shell treating the line as a continuation, and the Dockerfile is written verbatim.
    private const string CommandContinuation = " && \\\n    ";

    // Dockerfile RUN uses the shell form (/bin/sh -c), so user-supplied values such as bin target and feature
    // names must be quoted. Already-safe tokens (notably cargo's own flags) are left bare for readability.
    private static string ShellQuote(string value)
    {
        if (value.Length > 0 && value.All(static c => char.IsAsciiLetterOrDigit(c) || c is '-' or '_' or '.' or '/' or '=' or ',' or '+' or ':'))
        {
            return value;
        }

        // Single quotes suppress all shell expansion. An embedded single quote is emitted by closing the
        // quoted run, escaping the quote, then reopening: don't => 'don'\''t'.
        return $"'{value.Replace("'", "'\\''")}'";
    }

    // WithDockerfileBaseImage may be applied either to the Rust resource builder or, inside the
    // PublishAsDockerFile callback, to the substituted container resource.
    private static DockerfileBaseImageAnnotation? ResolveBaseImageAnnotation(RustAppResource resource, DockerfileBuilderCallbackContext context)
        => context.Resource.Annotations.OfType<DockerfileBaseImageAnnotation>().LastOrDefault()
            ?? resource.Annotations.OfType<DockerfileBaseImageAnnotation>().LastOrDefault();
}

#pragma warning restore ASPIREDOCKERFILEBUILDER001
