// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

#pragma warning disable ASPIREDOCKERFILEBUILDER001

using System.Collections.ObjectModel;
using Aspire.Hosting.ApplicationModel;
using Aspire.Hosting.ApplicationModel.Docker;
using Aspire.Hosting.Utils;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace Aspire.Hosting.Rust;

/// <summary>
/// Generates the multi-stage Dockerfile that publishes a <see cref="RustAppResource"/>.
/// </summary>
/// <remarks>
/// The container build is the only build: nothing here compiles the crate on the host.
/// </remarks>
internal static class RustDockerfileGenerator
{
    // rustup is present in the image and installs whatever a rust-toolchain.toml pins, so an unversioned tag
    // covers every channel. Runtime is pinned to a release so a rebuild cannot cross a major version.
    private const string DefaultBuildImage = "rust:alpine";
    private const string DefaultRuntimeImage = "alpine:3.24";

    // Kept outside /app so a .cargo/config.toml arriving with the build context cannot move the binary
    // somewhere COPY --from does not look.
    private const string ContainerTargetDirectory = "/build/target";
    private const string ContainerArtifactDirectory = "/build/bin";

    // Without this the local target/ directory, routinely several gigabytes, is uploaded to the daemon and
    // copied into the image by `COPY . .`. Cargo puts one next to every manifest, hence the recursive pattern.
    // See https://docs.docker.com/build/concepts/context/#filename-and-location.
    private const string DefaultRustBuildContextIgnoreContent = """
        # Generated by Aspire. Author <contextRoot>/.dockerignore to take over these rules.
        target
        **/target
        .git
        .gitignore
        .DS_Store
        .env
        .env.*
        .aspire
        aspire-output
        Dockerfile
        Dockerfile.*
        *.Dockerfile
        *.Dockerfile.dockerignore
        .dockerignore

        """;

    public static async Task WriteAsync(RustAppResource resource, DockerfileBuilderCallbackContext context)
    {
        var logger = context.Services.GetService<ILogger<RustAppResource>>();

        // Read from the resource so a WithWorkingDirectory applied after AddRustApp is honoured.
        var workingDirectory = Path.GetFullPath(resource.WorkingDirectory);

        // A <dockerfile>.dockerignore replaces the context root's .dockerignore rather than merging with it,
        // so an authored one wins outright.
        if (context.Resource.TryGetLastAnnotation<DockerfileBuildAnnotation>(out var dockerfileBuildAnnotation)
            && !File.Exists(Path.Combine(workingDirectory, ".dockerignore")))
        {
            dockerfileBuildAnnotation.BuildContextIgnoreContent ??= DefaultRustBuildContextIgnoreContent;
        }

        var options = resource.TryGetLastAnnotation<RustCargoOptionsAnnotation>(out var cargoOptions)
            ? cargoOptions
            : new RustCargoOptionsAnnotation();

        var containerManifestPath = ValidateManifestPath(options.ManifestPath, workingDirectory, resource.Name);

        var metadata = await context.Services.GetRequiredService<ICargoMetadataReader>()
            // Empty environment: the resource's environment applies to the process the container runs, not to
            // this host-side manifest query.
            .ReadAsync(workingDirectory, options.ManifestPath, resource.Name, ReadOnlyDictionary<string, string>.Empty, context.CancellationToken)
            .ConfigureAwait(false);

        var target = RustCargoTargetResolver.Resolve(
            metadata,
            options,
            context.Services.GetRequiredService<DistributedApplicationExecutionContext>(),
            resource.Name);

        // Read from `resource` rather than context.Resource because the latter is the ContainerResource that
        // PublishAsDockerFile substitutes in, which does not carry the Rust annotations.
        var cargoArgs = await ResolvePublishCargoArgsAsync(resource, context.CancellationToken).ConfigureAwait(false);

        if (options.ManifestPath is { } path && containerManifestPath is { } containerPath)
        {
            RewriteManifestPath(cargoArgs, path, containerPath);
        }

        // Images are used exactly as given and nothing is installed into either: a name is free-form, so an
        // image can be musl or glibc based regardless of what it is called. Pairing images that can run what
        // they build, including against any --target, belongs to whoever overrides them.
        var baseImageAnnotation = ResolveBaseImageAnnotation(resource, context);

        var buildStage = context.Builder
            .From(baseImageAnnotation?.BuildImage ?? DefaultBuildImage, "build")
            .WorkDir("/app");

        // A cross target's standard library is not present in the base image. This has to run after the source
        // is copied: rustup installs the target into the toolchain selected for the directory, so before the
        // copy it would land in the image default and a rust-toolchain.toml pin would build without it.
        var installTarget = target.Target is { } triple
            ? $"rustup target add {ShellQuote(triple)}{CommandContinuation}"
            : "";

        buildStage
            .Copy(".", ".")
            // RUSTUP_HOME cannot be cache mounted: mounts start empty and shadow what they cover, so one over
            // /usr/local/rustup hides the toolchains the image ships. The target directory is safe because the
            // selected binary is copied to ContainerArtifactDirectory while the mount is still live, and that
            // is what COPY --from reads. Lock the target cache because clearing stale candidates, building,
            // and collecting the current artifact must be atomic across concurrent BuildKit builds.
            .RunWithMounts(
                $"{installTarget}{BuildClearArtifactCommand(target)}{CommandContinuation}" +
                $"{BuildCargoCommand(cargoArgs)}{CommandContinuation}{BuildCollectArtifactCommand(target)}",
                "type=cache,target=/usr/local/cargo/registry",
                $"type=cache,target={ContainerTargetDirectory},sharing=locked");

        // Add intermediate FROM stages for any container files sources (e.g. FROM frontend AS frontend_stage).
        context.Builder.AddContainerFilesStages(context.Resource, logger);

        var runtimeStage = context.Builder.From(baseImageAnnotation?.RuntimeImage ?? DefaultRuntimeImage);

        // BusyBox and shadow-utils disagree on both command names and flags and the image may ship either, so
        // try one and fall back to the other. Ids are left to the tool to allocate because none is free on
        // every image: alpine already uses gid 999 for `ping`, and a taken id fails rather than falling through.
        runtimeStage.Run(
            "(addgroup -S app || groupadd --system app) && " +
            "(adduser -S -G app app || useradd --system --gid app --no-create-home app)");

        runtimeStage
            .WorkDir("/app")
            // Add COPY --from=<source> instructions for each container files source.
            .AddContainerFiles(context.Resource, "/app", logger)
            .CopyFrom("build", $"{ContainerArtifactDirectory}/{target.Name}", $"/app/{target.Name}")
            .User("app")
            .Entrypoint([$"/app/{target.Name}"]);
    }

    // Evaluates the same callbacks run mode does — the publish-only defaults come from AddInitialCargoArgs,
    // which sees the same execution context — then adds the container-only arguments.
    private static async Task<List<string>> ResolvePublishCargoArgsAsync(
        RustAppResource resource,
        CancellationToken cancellationToken)
    {
        var args = new List<string>();

        foreach (var annotation in resource.Annotations.OfType<RustCargoArgsCallbackAnnotation>())
        {
            await annotation.Callback(new RustCargoArgsCallbackContext(args, cancellationToken)).ConfigureAwait(false);
        }

        // Appended last because cargo takes the last occurrence of a flag.
        args.Add("--target-dir");
        args.Add(ContainerTargetDirectory);

        return args;
    }

    // Matches the two-token form WithCargoManifestPath emits. A --manifest-path passed as a raw string
    // through WithCargoArgs is left alone, in keeping with raw arguments being forwarded verbatim.
    private static void RewriteManifestPath(List<string> cargoArgs, string manifestPath, string containerPath)
    {
        for (var i = 0; i < cargoArgs.Count - 1; i++)
        {
            if (cargoArgs[i] == "--manifest-path" && cargoArgs[i + 1] == manifestPath)
            {
                cargoArgs[i + 1] = containerPath;
            }
        }
    }

    // Only the app directory is copied into the image, so the manifest has to sit inside it. Paths are
    // required to be relative because an absolute one can spell that same directory differently to us.
    private static string? ValidateManifestPath(string? manifestPath, string workingDirectory, string resourceName)
    {
        if (manifestPath is null)
        {
            return null;
        }

        if (Path.IsPathRooted(manifestPath))
        {
            throw new DistributedApplicationException(
                $"The Rust app '{resourceName}' builds from the absolute path '{manifestPath}'. Publishing needs a path " +
                $"relative to its app directory '{workingDirectory}'.");
        }

        var platformManifestPath = manifestPath
            .Replace('\\', Path.DirectorySeparatorChar)
            .Replace('/', Path.DirectorySeparatorChar);
        var canonicalWorkingDirectory = PathNormalizer.ResolveSymlinks(Path.GetFullPath(workingDirectory));
        var canonicalManifest = PathNormalizer.ResolveSymlinks(Path.GetFullPath(platformManifestPath, workingDirectory));
        var relativeManifest = Path.GetRelativePath(canonicalWorkingDirectory, canonicalManifest);

        if (Path.IsPathRooted(relativeManifest)
            || relativeManifest == ".."
            || relativeManifest.StartsWith($"..{Path.DirectorySeparatorChar}", StringComparison.Ordinal)
            || relativeManifest.StartsWith($"..{Path.AltDirectorySeparatorChar}", StringComparison.Ordinal))
        {
            throw new DistributedApplicationException(
                $"The Rust app '{resourceName}' builds from '{manifestPath}', which resolves outside its app directory " +
                $"'{workingDirectory}'. Only the app directory is copied into the image.");
        }

        // Rebase canonical-equivalent spellings (for example /var and /private/var on macOS) to the path
        // below the build context. The container only receives that relative layout.
        return relativeManifest.Replace('\\', '/');
    }

    private static string BuildCargoCommand(List<string> cargoArgs)
        => string.Join(" ", new[] { "cargo", "build" }.Concat(cargoArgs.Select(ShellQuote)));

    // The target directory is cache mounted, so remove every path that could satisfy the collector before
    // cargo runs. Deleting only the final executable preserves dependency and incremental build caches while
    // ensuring the current invocation has to materialize the one artifact the runtime stage will copy.
    private static string BuildClearArtifactCommand(RustCargoTarget target)
        => $"for candidate in {BuildArtifactCandidates(target)}; do if [ -f \"$candidate\" ]; then rm -f \"$candidate\"; fi; done";

    // Collects the binary to a fixed path so the runtime stage's COPY --from need not know whether cargo
    // inserted a target-triple directory. `--target` is only one way a triple is selected — `[build] target`
    // in a .cargo/config.toml arrives with the build context, and CARGO_BUILD_TARGET can come from the
    // resource environment — so both layouts are searched:
    //   /build/target/release/api            (no target selected)
    //   /build/target/x86_64-.../release/api (some target selected, by whatever means)
    // Only shell builtins plus the POSIX mkdir, cp, and rm utilities are used because the build image is
    // overridable. In particular, the generated build does not assume jq, grep, sed, or find are installed.
    private static string BuildCollectArtifactCommand(RustCargoTarget target)
    {
        var destination = $"{ContainerArtifactDirectory}/{ShellQuote(target.Name)}";

        return string.Join(
            CommandContinuation,
            [
                "count=0",
                // An unmatched glob stays literal, so each candidate is tested rather than counted.
                $"for candidate in {BuildArtifactCandidates(target)}; do if [ -f \"$candidate\" ]; then bin=\"$candidate\"; count=$((count+1)); fi; done",
                // `if` rather than `[ ... ] || { ... }`: && and || share precedence and associate left to right,
                // so a trailing || catches the whole preceding chain and reports this on top of cargo's own error.
                $"if [ \"$count\" = 0 ]; then echo \"no {ShellQuote(target.Name)} under {ContainerTargetDirectory}\" >&2; exit 1; fi",
                $"if [ \"$count\" != 1 ]; then echo \"found $count {ShellQuote(target.Name)} under {ContainerTargetDirectory} after cargo build\" >&2; exit 1; fi",
                $"mkdir -p {ContainerArtifactDirectory}",
                $"cp \"$bin\" {destination}"
            ]);
    }

    private static string BuildArtifactCandidates(RustCargoTarget target)
    {
        // Quoting only the suffix keeps the wildcard live: quoting the whole path would make the `*` literal.
        var suffix = ShellQuote(target.RelativePathWithoutTarget);

        return $"{ContainerTargetDirectory}/{suffix} {ContainerTargetDirectory}/*/{suffix}";
    }

    // An explicit LF rather than Environment.NewLine: a CR after the backslash stops the shell treating the
    // line as a continuation, and the Dockerfile is written verbatim.
    private const string CommandContinuation = " && \\\n    ";

    // Dockerfile RUN uses the shell form (/bin/sh -c), so user-supplied values such as bin target and feature
    // names must be quoted. Already-safe tokens are left bare for readability.
    private static string ShellQuote(string value)
    {
        if (value.Length > 0 && value.All(static c => char.IsAsciiLetterOrDigit(c) || c is '-' or '_' or '.' or '/' or '=' or ',' or '+' or ':'))
        {
            return value;
        }

        // An embedded single quote is emitted by closing the quoted run, escaping it, then reopening:
        // don't => 'don'\''t'.
        return $"'{value.Replace("'", "'\\''")}'";
    }

    // WithDockerfileBaseImage may be applied to the Rust resource builder or, inside the PublishAsDockerFile
    // callback, to the substituted container resource.
    private static DockerfileBaseImageAnnotation? ResolveBaseImageAnnotation(RustAppResource resource, DockerfileBuilderCallbackContext context)
        => context.Resource.Annotations.OfType<DockerfileBaseImageAnnotation>().LastOrDefault()
            ?? resource.Annotations.OfType<DockerfileBaseImageAnnotation>().LastOrDefault();
}

#pragma warning restore ASPIREDOCKERFILEBUILDER001
